import { boolean, integer, json, pgTable, real, text, timestamp, varchar } from "drizzle-orm/pg-core";
import type { Feature, Faq, OrderItem, ProductImage, Spec } from "@/lib/types";

export const products = pgTable("products", {
  id: varchar("id", { length: 64 }).primaryKey(),
  slug: varchar("slug", { length: 160 }).notNull().unique(),
  sku: varchar("sku", { length: 64 }).notNull(),
  name: varchar("name", { length: 200 }).notNull(),
  seoTitle: varchar("seo_title", { length: 200 }).notNull().default(""),
  seoDescription: text("seo_description").notNull().default(""),
  tagline: text("tagline").notNull().default(""),
  brand: varchar("brand", { length: 80 }).notNull().default("ElectroMov"),
  categorySlug: varchar("category_slug", { length: 80 }).notNull(),
  status: varchar("status", { length: 20 }).notNull().default("published"),
  featured: boolean("featured").notNull().default(false),
  priceUsd: real("price_usd").notNull().default(0),
  compareAtUsd: real("compare_at_usd").notNull().default(0),
  priceConfirmed: boolean("price_confirmed").notNull().default(false),
  stock: integer("stock").notNull().default(0),
  shortDescription: text("short_description").notNull().default(""),
  longDescription: json("long_description").$type<string[]>().notNull().default([]),
  highlights: json("highlights").$type<string[]>().notNull().default([]),
  features: json("features").$type<Feature[]>().notNull().default([]),
  specs: json("specs").$type<Spec[]>().notNull().default([]),
  faqs: json("faqs").$type<Faq[]>().notNull().default([]),
  images: json("images").$type<ProductImage[]>().notNull().default([]),
  badges: json("badges").$type<string[]>().notNull().default([]),
  connectors: json("connectors").$type<string[]>().notNull().default([]),
  keywords: json("keywords").$type<string[]>().notNull().default([]),
  crossSell: json("cross_sell").$type<string[]>().notNull().default([]),
  powerKw: real("power_kw").notNull().default(0),
  amps: integer("amps").notNull().default(0),
  phases: integer("phases").notNull().default(1),
  warrantyMonths: integer("warranty_months").notNull().default(12),
  weightKg: real("weight_kg").notNull().default(0),
  requiresElectrician: boolean("requires_electrician").notNull().default(false),
  gtin: varchar("gtin", { length: 32 }),
  mpn: varchar("mpn", { length: 64 }).notNull().default(""),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const settings = pgTable("settings", {
  key: varchar("key", { length: 64 }).primaryKey(),
  value: json("value").$type<unknown>().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const orders = pgTable("orders", {
  id: varchar("id", { length: 64 }).primaryKey(),
  reference: varchar("reference", { length: 32 }).notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  status: varchar("status", { length: 24 }).notNull().default("pending"),
  customerName: varchar("customer_name", { length: 160 }).notNull().default(""),
  customerEmail: varchar("customer_email", { length: 160 }).notNull().default(""),
  customerPhone: varchar("customer_phone", { length: 60 }).notNull().default(""),
  customerDoc: varchar("customer_doc", { length: 40 }).notNull().default(""),
  shippingMethod: varchar("shipping_method", { length: 24 }).notNull().default("pickup"),
  shippingAddress: text("shipping_address").notNull().default(""),
  shippingCity: varchar("shipping_city", { length: 120 }).notNull().default(""),
  shippingZip: varchar("shipping_zip", { length: 20 }).notNull().default(""),
  shippingProvince: varchar("shipping_province", { length: 80 }).notNull().default(""),
  notes: text("notes").notNull().default(""),
  items: json("items").$type<OrderItem[]>().notNull().default([]),
  subtotalArs: integer("subtotal_ars").notNull().default(0),
  shippingArs: integer("shipping_ars").notNull().default(0),
  totalArs: integer("total_ars").notNull().default(0),
  usdRate: real("usd_rate").notNull().default(0),
  mpPreferenceId: varchar("mp_preference_id", { length: 120 }).notNull().default(""),
  mpPaymentId: varchar("mp_payment_id", { length: 120 }).notNull().default(""),
  paymentMethod: varchar("payment_method", { length: 60 }).notNull().default(""),
  installments: integer("installments").notNull().default(1),
});

export const leads = pgTable("leads", {
  id: varchar("id", { length: 64 }).primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  source: varchar("source", { length: 60 }).notNull().default("asesor"),
  name: varchar("name", { length: 160 }).notNull().default(""),
  email: varchar("email", { length: 160 }).notNull().default(""),
  phone: varchar("phone", { length: 60 }).notNull().default(""),
  payload: json("payload").$type<Record<string, unknown>>().notNull().default({}),
});
